pipeline {
    agent none

    stages {

        stage('Back-end') {
            agent {
                docker {
                    image 'maven:3.9.11-eclipse-temurin-21'
                }
            }
            steps {
                sh 'java -version'
                sh 'mvn --version'
            }
        }

        stage('Front-end') {
            agent {
                docker {
                    image 'node:22-alpine'
                }
            }
            steps {
                sh 'node --version'
                sh 'npm --version'
            }
        }

    }
}
